<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>693ce91a-f485-4a46-8ee9-393eac873d42</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(3) &gt; :nth-child(4) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(3) &gt; :nth-child(1) &gt; :nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-outline-secondary text-center')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-outline-secondary text-center</value>
        <webElementGuid>9c4bcbeb-2fef-44f2-ae90-b57064165829</webElementGuid>
    </webElementProperties>
</WebElementEntity>