<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f3751137-f778-4933-96ac-f5c62c6ef77e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.mars-logo-row__at-right .cart-header</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cart-header cart-header_empty')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cart-header cart-header_empty</value>
        <webElementGuid>6d1e5e91-b3de-4ddc-b1f1-4969a38d1db4</webElementGuid>
    </webElementProperties>
</WebElementEntity>