<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b9ed6e57-fcf5-4501-ac1e-5314a8881a9b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/p[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.btn-success</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-success')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-success</value>
        <webElementGuid>108e5016-eeef-4144-bf3b-77b613aaa5ee</webElementGuid>
    </webElementProperties>
</WebElementEntity>