<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0dbb2bfb-5c4e-4bfe-b5c3-a9209c12ca95</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-contact-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'bdl-contact-form one-field')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>bdl-contact-form one-field</value>
        <webElementGuid>b7def7dd-5c73-4a55-bbdd-7478c9f333f2</webElementGuid>
    </webElementProperties>
</WebElementEntity>