<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>95eb1861-b1fc-442f-807f-528d295a4213</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/p[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.MuiButton-text</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeSmall MuiButton-textSizeSmall css-1fnkzhd')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeSmall MuiButton-textSizeSmall css-1fnkzhd</value>
        <webElementGuid>297d1ea0-c5fd-4746-8334-19affdf36977</webElementGuid>
    </webElementProperties>
</WebElementEntity>